# Generated by Django 3.2.4 on 2021-06-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertReferences',
            new_name='AlertReference',
        ),
    ]
